stages:
  - build
  - test

variables:
  PHP_VERSION: "8.1"
  OPERATING_SYSTEM: "ubuntu-latest"
  CODECOV_TOKEN: $CODECOV_TOKEN

before_script:
  - apt-get update -y
  - apt-get install -y curl git unzip
  - composer --version || curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  - composer install --prefer-dist --no-progress --no-suggest
  - pecl install xdebug
  - docker-php-ext-enable xdebug  

build_job:
  stage: build
  image: "php:${PHP_VERSION}"
  script:
    - git checkout .
    - composer validate --strict

test_job:
  stage: test
  image: "php:${PHP_VERSION}"
  script:
    - vendor/bin/php-cs-fixer fix --dry-run --show-progress=none -vvv
    - vendor/bin/phpstan analyze
    - XDEBUG_MODE=coverage vendor/bin/phpunit --coverage-clover clover.xml
    - pwd
    - ls -la
    - ls /vendor/bin/phpunit
    - php -v

  artifacts:
    paths:
      - clover.xml
    reports:
      coverage_report:
        coverage_format: cobertura
        path: clover.xml
  coverage: '/<metrics[^>]*?statements[^>]*?covered="([^"]+)"/'