stages:
  - build
  - test

variables:
  PHP_VERSION: "8.1"
  OPERATING_SYSTEM: "ubuntu-latest"
  CODECOV_TOKEN: $CODECOV_TOKEN

before_script:
  - apt-get update -y
  - apt-get install -y curl git unzip
  - composer --version || curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  - composer install --prefer-dist --no-progress --no-suggest

build_job:
  stage: build
  image: "php:${PHP_VERSION}"
  script:
    - git checkout .
    - composer validate --strict

test_job:
  stage: test
  image: "php:${PHP_VERSION}"
  script:
    - vendor/bin/php-cs-fixer fix --dry-run --show-progress=none -vvv
    - vendor/bin/phpstan analyze
    - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

  artifacts:
    paths:
      - build/logs/clover.xml
    reports:
      coverage_report:
        coverage_format: cobertura
        path: build/logs/clover.xml
  coverage: '/<metrics[^>]*?statements[^>]*?covered="([^"]+)"/'