<?php declare(strict_types = 1);

namespace SandwaveIo\RealtimeRegister\Domain\Enum;

enum BillableActionEnum: string
{
    case ACTION_CREATE = 'CREATE';
    case ACTION_REQUEST = 'REQUEST';
    case ACTION_TRANSFER = 'TRANSFER';
    case ACTION_RENEW = 'RENEW';
    case ACTION_RESTORE = 'RESTORE';
    case ACTION_TRANSFER_RESTORE = 'TRANSFER_RESTORE';
    case ACTION_UPDATE = 'UPDATE';
    case ACTION_REGISTRANT_CHANGE = 'REGISTRANT_CHANGE';
    case ACTION_LOCAL_CONTACT = 'LOCAL_CONTACT';
    case ACTION_NEGATIVE_MARKUP = 'NEGATIVE_MARKUP';
    case ACTION_PRIVACY_PROTECT = 'PRIVACY_PROTECT';
    case ACTION_EXTRA_WILDCARD = 'EXTRA_WILDCARD';
    case ACTION_EXTRA_DOMAIN = 'EXTRA_DOMAIN';
    case ACTION_REGISTRY_LOCK = 'REGISTRY_LOCK';
}
