<?php declare(strict_types = 1);

namespace SandwaveIo\RealtimeRegister\Domain\Enum;

class DomainStatusEnum extends AbstractEnum
{
    const STATUS_OK = 'OK';
    const STATUS_INACTIVE = 'INACTIVE';
    const STATUS_PENDING_TRANSFER = 'PENDING_TRANSFER';
    const STATUS_PENDING_RENEW = 'PENDING_RENEW';
    const STATUS_PENDING_UPDATE = 'PENDING_UPDATE';
    const STATUS_DELETE_REQUESTED = 'DELETE_REQUESTED';
    const STATUS_PENDING_DELETE = 'PENDING_DELETE';
    const STATUS_ADD_PERIOD = 'ADD_PERIOD';
    const STATUS_RENEW_PERIOD = 'RENEW_PERIOD';
    const STATUS_AUTO_RENEW_PERIOD = 'AUTO_RENEW_PERIOD';
    const STATUS_TRANSFER_PERIOD = 'TRANSFER_PERIOD';
    const STATUS_REDEMPTION_PERIOD = 'REDEMPTION_PERIOD';
    const STATUS_PENDING_RESTORE = 'PENDING_RESTORE';
    const STATUS_CLIENT_HOLD = 'CLIENT_HOLD';
    const STATUS_CLIENT_DELETE_PROHIBITED = 'CLIENT_DELETE_PROHIBITED';
    const STATUS_CLIENT_UPDATE_PROHIBITED = 'CLIENT_UPDATE_PROHIBITED';
    const STATUS_CLIENT_RENEW_PROHIBITED = 'CLIENT_RENEW_PROHIBITED';
    const STATUS_CLIENT_TRANSFER_PROHIBITED = 'CLIENT_TRANSFER_PROHIBITED';
    const STATUS_REGISTRAR_HOLD = 'REGISTRAR_HOLD';
    const STATUS_REGISTRAR_DELETE_PROHIBITED = 'REGISTRAR_DELETE_PROHIBITED';
    const STATUS_REGISTRAR_UPDATE_PROHIBITED = 'REGISTRAR_UPDATE_PROHIBITED';
    const STATUS_REGISTRAR_RENEW_PROHIBITED = 'REGISTRAR_RENEW_PROHIBITED';
    const STATUS_REGISTRAR_TRANSFER_PROHIBITED = 'REGISTRAR_TRANSFER_PROHIBITED';
    const STATUS_SERVER_HOLD = 'SERVER_HOLD';
    const STATUS_SERVER_DELETE_PROHIBITED = 'SERVER_DELETE_PROHIBITED';
    const STATUS_SERVER_UPDATE_PROHIBITED = 'SERVER_UPDATE_PROHIBITED';
    const STATUS_SERVER_RENEW_PROHIBITED = 'SERVER_RENEW_PROHIBITED';
    const STATUS_SERVER_TRANSFER_PROHIBITED = 'SERVER_TRANSFER_PROHIBITED';
    const STATUS_PENDING_VALIDATION = 'PENDING_VALIDATION';
    const STATUS_PRIVACY_PROTECT_PROHIBITED = 'PRIVACY_PROTECT_PROHIBITED';
    const STATUS_EXPIRED = 'EXPIRED';
    const STATUS_IRTPC_TRANSFER_PROHIBITED = 'IRTPC_TRANSFER_PROHIBITED';

    protected static $values = [
        DomainStatusEnum::STATUS_OK,
        DomainStatusEnum::STATUS_INACTIVE,
        DomainStatusEnum::STATUS_PENDING_TRANSFER,
        DomainStatusEnum::STATUS_PENDING_RENEW,
        DomainStatusEnum::STATUS_PENDING_UPDATE,
        DomainStatusEnum::STATUS_DELETE_REQUESTED,
        DomainStatusEnum::STATUS_PENDING_DELETE,
        DomainStatusEnum::STATUS_ADD_PERIOD,
        DomainStatusEnum::STATUS_RENEW_PERIOD,
        DomainStatusEnum::STATUS_AUTO_RENEW_PERIOD,
        DomainStatusEnum::STATUS_TRANSFER_PERIOD,
        DomainStatusEnum::STATUS_REDEMPTION_PERIOD,
        DomainStatusEnum::STATUS_PENDING_RESTORE,
        DomainStatusEnum::STATUS_CLIENT_HOLD,
        DomainStatusEnum::STATUS_CLIENT_DELETE_PROHIBITED,
        DomainStatusEnum::STATUS_CLIENT_UPDATE_PROHIBITED,
        DomainStatusEnum::STATUS_CLIENT_RENEW_PROHIBITED,
        DomainStatusEnum::STATUS_CLIENT_TRANSFER_PROHIBITED,
        DomainStatusEnum::STATUS_REGISTRAR_HOLD,
        DomainStatusEnum::STATUS_REGISTRAR_DELETE_PROHIBITED,
        DomainStatusEnum::STATUS_REGISTRAR_UPDATE_PROHIBITED,
        DomainStatusEnum::STATUS_REGISTRAR_RENEW_PROHIBITED,
        DomainStatusEnum::STATUS_REGISTRAR_TRANSFER_PROHIBITED,
        DomainStatusEnum::STATUS_SERVER_HOLD,
        DomainStatusEnum::STATUS_SERVER_DELETE_PROHIBITED,
        DomainStatusEnum::STATUS_SERVER_UPDATE_PROHIBITED,
        DomainStatusEnum::STATUS_SERVER_RENEW_PROHIBITED,
        DomainStatusEnum::STATUS_SERVER_TRANSFER_PROHIBITED,
        DomainStatusEnum::STATUS_PENDING_VALIDATION,
        DomainStatusEnum::STATUS_PRIVACY_PROTECT_PROHIBITED,
        DomainStatusEnum::STATUS_EXPIRED,
        DomainStatusEnum::STATUS_IRTPC_TRANSFER_PROHIBITED,
    ];

    /** @param string $value */
    public static function validate($value): void
    {
        DomainStatusEnum::assertValueValid($value);
    }
}
